### ISSUE TITLE
Animation and Transition Actions

### ISSUE THREAD

**Issue by devinhalladay** [splatcollision/shorthand.js#1]
For the syntax, how about we use somthing like

``` js
#button1 should slide #panel1 in from the left on click
#button2 should slide #panel2 out to the left on click
```

I have no idea if that's even possible at this point—I haven't had time to look through the code—but I saw the last line of the README and thought I'd at least share my thoughts. :+1:

**Comment by mikefats** [comment]
In case there are more precise animation attributes introduced in the future, would it make sense to make them two-part sentences like so?

`#button1 should animate #panel1 on click: slide in from the left`
`#button1 should animate #panel1 on click: slide out slow from the right`
`#button1 should animate #panel1 on click: slide in fast from the top`
`#button1 should animate #panel1 on click: rotate 180 degrees`
`#button1 should animate #panel1 on click: flip out of view horizontally`
`#button1 should animate #panel1 on click: flip into view horizontally`
`#button1 should animate #panel1 on click: shake fast 4 times`

**Comment by devinhalladay** [comment]
Yeah I definitely think that's a good idea. That would probably make it much easier to parse the animation strings as well.

**Comment by splatcollision** [comment]
Devin / Mike - Sorry for not seeing these earlier - these are great suggestions and I will look and see what's feasable & what makes the most sense. I was hoping to include something like http://daneden.github.io/animate.css/ so that there would be sets of readily-available animations to reference. I would tend to like to keep the syntax english-like without special characters (except css selectors!)
