### ISSUE TITLE
Does not detect jquery

### ISSUE THREAD

**Issue by chasegiunta** [splatcollision/shorthand.js#3]
Looks like this script isn't detecting jQuery. It's definitely being loaded in the browser. Any workarounds, suggestions?

**Comment by splatcollision** [comment]
Hi - Thanks for the issue.

Is it working as expected and just throwing the warning in the console? or is the script not working at all? You might try uncommenting and adding back the conditionals on [this line](https://github.com/splatcollision/shorthand.js/blob/1c920b0f8b4ad564c0d3c5e5cf1ed626c47929b8/shorthand.js#L21) so it checks for more than just window.jQuery? 

Otherwise if you can post a test case, I'll look at it. Thanks!
